### ISSUE TITLE
Submitting transaction doesn't work

### ISSUE THREAD

**Issue by s-a-y** [kinecosystem/kin-node#13]
Since about 15 Dec can't submit any transactions, getting this:
```
error:  ReferenceError: BigInt is not defined
    at Client.<anonymous> (/home/xxx/node_modules/@kinecosystem/kin-sdk-v2/dist/client/client.js:490:51)
    at Generator.next (<anonymous>)
    at /home/xxx/node_modules/@kinecosystem/kin-sdk-v2/dist/client/client.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/xxx/node_modules/@kinecosystem/kin-sdk-v2/dist/client/client.js:4:12)
    at Client.submitSolanaPayment (/home/xxx/node_modules/@kinecosystem/kin-sdk-v2/dist/client/client.js:452:16)
    at Client.<anonymous> (/home/xxx/node_modules/@kinecosystem/kin-sdk-v2/dist/client/client.js:426:37)
    at Generator.next (<anonymous>)
    at fulfilled (/home/xxx/node_modules/@kinecosystem/kin-sdk-v2/dist/client/client.js:5:58)
    at <anonymous>
```

Tried updating to the latest version 0.3.10, it's the same.

**Comment by EpicApex** [comment]
Any news regarding this?

**Comment by showered** [comment]
`BigInt` is built-in to Node v10+ so make sure your Node is relatively up to date.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
